import { Box } from '@mui/material'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { SideMenu } from '../components/SideMenu/SideMenu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className} style={{ padding: 0, margin: 0, boxSizing: "border-box" }}>
        <Box bgcolor="#dddddd" minHeight="100vh">
          <SideMenu>
            {children}
          </SideMenu>
        </Box>
      </body>
    </html>
  )
}
